"""empty message

Revision ID: 0f4c3f587dfa
Revises: f84f6b20b9a7
Create Date: 2024-06-14 08:50:49.719677

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4c3f587dfa'
down_revision = 'f84f6b20b9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('opt_type', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.drop_column('opt_type')
        batch_op.drop_column('objective')

    # ### end Alembic commands ###
