"""empty message

Revision ID: 2de939c4e8a2
Revises: 0f4c3f587dfa
Create Date: 2024-06-21 02:42:09.567710

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de939c4e8a2'
down_revision = '0f4c3f587dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.alter_column('objective',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.alter_column('objective',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
