"""empty message

Revision ID: 66bf12a8cf59
Revises: 4e99a8df00ff
Create Date: 2024-06-13 10:02:43.512269

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bf12a8cf59'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_operation_logs',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.StringUUID(), nullable=False),
    sa.Column('group_id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=False),
    sa.Column('created_by', models.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='dataset_operation_logs_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_operation_logs')
    # ### end Alembic commands ###
