"""empty message

Revision ID: f84f6b20b9a7
Revises: 66bf12a8cf59
Create Date: 2024-06-14 07:44:03.370272

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84f6b20b9a7'
down_revision = '66bf12a8cf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_operation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
